Develop
frontend-park-mail-ru/2019_1_WAO pull request #1
Opened 2019-03-10 21:15 UTC by Vlad104

1) Страницы: вход, регистрация, меню, таблица лидеров, профиль - все SPA
2) Обмен данными с сервером с помощью ajax: страницы вход, регистрация,, профиль и таблица лидеров
2) Настроен webpack на генерацию html станицы и одного файла js
3) Подключен ESLint
4) Используем шаблонизатор fest
5) Деплой на хероку https://wao2019.herokuapp.com/
6) в папке /public/page - старый код
7) Запуск:
npm install
npm run build
npm start

2019-03-27 22:06 UTC, stanf0rd requested changes

2019-03-27 22:06 UTC, stanf0rd commented on public/modules/ajax.js
> +  doPromiseGet({path = '/'} = {}) {
Что это?) Зачем, если есть fetch?

2019-03-27 22:06 UTC, stanf0rd commented on public/modules/ajax.js
> +const Ajax = new AjaxModule();
Можно сразу
```javascript
export new AjaxModule();
```
Просмотри везде в файликах глобальным поиском

2019-03-27 22:06 UTC, stanf0rd commented on public/modules/api.js
> +export default class Api {
Какой смысл делать класс, если в нём только статические методы?
Лучше заэкспортировать эти функции.
Заодно можно будет импортить только, те что надо.

2019-03-27 22:06 UTC, stanf0rd commented on public/modules/api.js
> +	static getUser(nickname) {
Ну и раз уж так старательно описывать всё js-доками, напиши, что оно возвращает. В теории, jsdoc нужен, чтобы можно было понять, как этим пользоваться. Я вот, прочитав доки, вообще не представляю, как :) Мне придётся вручную вызвать эту функцию и рассмотреть, а чо оно вернёт

2019-03-27 22:06 UTC, stanf0rd commented on public/modules/auth.js
> +		this._reject = reject;
что это?)

2019-03-27 22:06 UTC, stanf0rd commented on public/modules/auth.js
> +          if (xhr.status === 200 || xhr.status === 304) {
У вас есть xhr в аякс-модуле, xhr, завёрнутый в промис там же, кусочки fetch api там же, а здесь... промис, который... что-то делает с xhr... очень сложно :(

Я так понимаю, эта штука проверяет залогиненность?
Почему бы просто не сделать в файлике api.js метод, который ходит за юзером, и заюзать его здесь? С `then`/`catch`, если через промисы, или с `await` и чекать ошибку.

2019-03-27 22:06 UTC, stanf0rd commented on public/modules/user.js
> +  get() {
Зачем такое?
Выглядит, как геттеры и сеттеры из плюсов. Так в js не делают)
У вас есть обычный объект user, в нём есть поля, обращайтесь к ним через точку, и всё. Если хочется получать объект - используйте деструктуризацию:
```javascript
const { nickname, email, image } = user;
```

2019-03-27 22:06 UTC, stanf0rd commented on public/modules/user.js
> +  reset() {
Опять же, в этом нет смысла - у вас где-то хранится переменная user, если вы разлогинились, или что-то случилось, обнуляйте её. Обнулять все её поля, но оставлять её саму смысла нет.

2019-03-27 22:06 UTC, stanf0rd commented on public/modules/user.js
> +    this.image		= null;
Такой конструктор не имеет смысла, его проще оставить пустым

2019-03-27 22:06 UTC, stanf0rd commented on public/presenters/MenuPresenter.js
> +	constructor(Router, globalEventBus) {
Зачем передавать bus в конструктор, если выше есть импорт файла с ним?

2019-03-27 22:06 UTC, stanf0rd commented on public/presenters/MenuPresenter.js
> +		const eventBus = new EventBus();
А globalEventBus зачем? Переменная не используется
Или их планируется сделать два, один локальный, другой глобальный? Тогда зачем их два))

2019-03-27 22:06 UTC, stanf0rd commented on public/presenters/ProfilePresenter.js
> +		const eventBus = new EventBus();
ещё один bus?

2019-03-27 22:06 UTC, stanf0rd commented on public/presenters/RulesPresenter.js
> +		const eventBus = new EventBus();
и ещё?
тут что-то не так

2019-03-27 22:06 UTC, stanf0rd commented on public/presenters/RulesPresenter.js
> +		const eventBus = new EventBus();
К слову, globalEventBus по-прежнему не используется

2019-03-27 22:06 UTC, stanf0rd commented on public/presenters/RulesPresenter.js
> +export default class RulesPresenter {
Что такое Presenter?
Вижу много повторяющегося кода в конструкторах этих штук. Если в этих Presenter-ах есть смысл, то тогда стоит сделать некий BasePresenter
(о том, что этот код делает, отдельный разговор)

2019-03-27 22:06 UTC, stanf0rd commented on public/routers_functions.js
> +    scoreboard.data = JSON.parse(JSON.stringify(users));
Зачем сначала stringify, а потом parse?

2019-03-27 22:06 UTC, stanf0rd commented on public/routers_functions.js
> +      callback(xhr) {
обсуждали странность таких запросов
Лучше через fetch api с async/await

У вас для таких штук есть обёртка api.js

2019-03-27 22:06 UTC, stanf0rd commented on public/routers_functions.js
> +  const form = document.getElementsByTagName('form')[0];
Я писал про деструктуризацию
`[0]` делать фу)
В таких случаях надо так:
```javascript
const [form] = document.getElementsByTagName('form');
```

2019-03-27 22:06 UTC, stanf0rd commented on public/routers_functions.js
> +  const buttonImg = document.getElementById('buttonImg');
Опасно использовать id, лучше искать по классу внутри конкретного блока. Знаете ведь, что можно искать элементы не только внутри document, но и внутри любого элемента в принципе? И чем глубже и меньше этот элемент, тем быстрее идёт поиск по ним

2019-03-27 22:06 UTC, stanf0rd commented on public/routers_functions.js
> +    formData.append('image', inputImg.files[0]);
Сама формдата картинку не подтягивает?
Должна

2019-03-27 22:06 UTC, stanf0rd commented on public/routers_functions.js
> +                User.update();
У вас настроен линтер на избыточную вложенность? Такие штуки очень сложно читать.
коллбэк в стрелочной функции в листенере в кэтче промиса в функции, ух бл

Но и даже если без линтера, есть смысл подумать, всё ли вы делаете хорошо, если приходится такое городить

2019-03-27 22:06 UTC, stanf0rd commented on public/routers_functions.js
> +                User.update();
К слову, городить приходится потому, что не доделаны обёртки в api.js
Вам надо их сделать (3)

2019-03-27 22:06 UTC, stanf0rd commented on public/routers_functions.js
> +  const footer = document.getElementsByClassName('registration_input_footer_divblock_registration')[0];
вау, что это?
Очень адские имена классов
Они генерятся как-то?
У вас есть компоненты? Можно делать поиск внутри них, не по document. Тогда и такие страшные имена не понадобятся.

2019-03-27 22:06 UTC, stanf0rd commented on public/routers_functions.js
> +    if (!email.match(/^([a-z0-9_\-]+\.)*[a-z0-9_\-]+@([a-z0-9][a-z0-9\-]*[a-z0-9]\.)+[a-z]{2,4}$/i)){
Не стоит делать такие штуки вообще
Как вы заебались это вводить, что закомментили, так и любой другой заебется вводить паленую почту, потому что свою почту палить никто не любит, и так спам некуда девать))

2019-03-27 22:06 UTC, stanf0rd commented on public/utils/constants.js
> +  menu: routerPrexix + '/',
лучше использовать такие штуки вместо `+`
```javascript
`${routerPrefix}/`
```

2019-03-27 22:06 UTC, stanf0rd commented on public/views/profile/profile.css
> +.profile_container .profile_container_top .profile_data_1 .profile_data_bottom_border_div, .profile_container .profile_container_top .profile_data_2 .profile_data_bottom_border_div, .profile_containe
боги
пока что никто не смотрит на вёрстку, так что пусть
но в будущем такого быть не должно

2019-03-27 22:06 UTC, stanf0rd commented on public/views/signin/signin.tmpl.xml
> +                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8.614 8.147h2.097s.217-.663.289-1.62v-.148.074-.368H8.542v
xml лучше вынести в отдельные пикчефайлы и раздавать как статику

2019-03-27 22:06 UTC, stanf0rd commented on webpack.config.js
> +      /* Пока вручную, а то и без него проблем не мало
1) настройте eslint в IDE! Это гораздо важнее, чем просто препроверка при запуске
2) вы ведь исправляете его ошибки, правда? надо будет потом чекнуть :)

2019-03-27 22:06 UTC, stanf0rd commented on .eslintrc.js
> +    "extends": "google",
лучше используйте airbnb, это стандартный конфиг в мире js

2019-03-27 22:06 UTC, stanf0rd commented on public/components/Menu/Menu.js
> +    this._el = el;
а зачем нижнее подчёркивание?
хотите отметить, что это приватные методы? так ли это надо?)

2019-03-27 22:06 UTC, stanf0rd commented on public/components/Menu/Menu.js
> +  set data(d = []) {
1) зачем такой сеттер вообще нужен? если есть обращение через точку
2) почему пустой массив по умолчанию, а не объект?

2019-03-27 22:06 UTC, stanf0rd commented on public/components/Profile/profile.js
> +    this._type = type;
Повторюсь - здесь и много-много эти нижние подчёркивания не имеют смысла, т.к. к ним всё равно есть доступ, и единственное, что они делают - это ухудшают читаемость

2019-03-27 22:06 UTC, stanf0rd commented on public/components/Profile/profile.js
> +    this._type = type;
Изредка они полезны, но только в случае, когда у вас есть какой-то очень-очень опасный метод, который очень нельзя заюзать снаружи. Или когда есть метод `render()`, который дёргает пользователь либы/класса, и метод `__render()`, который дёргается в самой либе, в недрах метода `render()`, перед которым происходит какая-нить настройка, вызывается `prerender()` и так далее

2019-03-27 22:09 UTC, Vlad104 commented on public/modules/ajax.js
> +  doPromiseGet({path = '/'} = {}) {
Это старый файл, им не пользуемся. Все походы в сеть через api,js и там только fetch

2019-03-27 22:12 UTC, Vlad104 commented on public/modules/auth.js
> +		this._reject = reject;
auth.js тоже не используем. эти строчки я даже не успел дописать, сразу закомментил

2019-03-27 23:35 UTC, Vlad104 commented on public/presenters/MenuPresenter.js
> +	constructor(Router, globalEventBus) {
Здесь предполагается, что будет передаваться глобальная шина событий.
Импорт нужен для создания локальной шины, по которой связываются модель вьюха и пресентер

2019-03-27 23:36 UTC, Vlad104 commented on public/presenters/RulesPresenter.js
> +		const eventBus = new EventBus();
до globalEventBus руки еще не дошли)

2019-03-27 23:37 UTC, Vlad104 commented on public/routers_functions.js
> +    scoreboard.data = JSON.parse(JSON.stringify(users));
в этот файл лучше не смотреть. это старый код. но там может быть что-то полезное, поэтому его не удаляем

2019-04-02 18:29 UTC, stanf0rd requested changes

2019-04-02 18:29 UTC, stanf0rd commented on .eslintrc.js
> +            "jsx": true
Зачем это?)

2019-04-02 18:29 UTC, stanf0rd commented on dist/main.bundle.js
> +!function(r){var n={};function t(e){if(n[e])return n[e].exports;var o=n[e]={i:e,l:!1,exports:{}};return r[e].call(o.exports,o,o.exports,t),o.l=!0,o.exports}t.m=r,t.c=n,t.d=function(r,n,e){t.o(r,n)||O
Ахтунг, бинари в репе

2019-04-02 18:29 UTC, stanf0rd commented on dist/main.bundle.js.map
> +{"version":3,"sources":["webpack:///webpack/bootstrap","webpack:///./node_modules/css-loader/dist/runtime/api.js","webpack:///./node_modules/style-loader/lib/addStyles.js","webpack:///./public/img/us
Бинари в репе 2

2019-04-02 18:29 UTC, stanf0rd commented on package.json
> +    "eslint-config-google": "^0.12.0",
У вас же airbnb конф, зачем гугловый рядом? Почисть ненужные пакеты

2019-04-02 18:29 UTC, stanf0rd commented on package.json
> +    "eslint-plugin-react": "^7.11.0",
Зачем оно здесь?)

2019-04-02 18:29 UTC, stanf0rd commented on public/components/ScoreProfile/ScoreProfile.html
> +	<title>Score Board</title>
Судя по тому, как выглядит гит, у вас поломана табуляция. Где-то пробелы, где-то табы, причём разное количество. В настройках visual studio code, если вы им пользуетесь, есть классная опция render whitespaces, которая показывает пробелы и табы. А ещё есть опция, удаляющая пробелы в концах строк при сохранении файлов. Рекомендую

Кстати, а у вас табы или пробелы?)

2019-04-02 18:29 UTC, stanf0rd commented on public/components/ScoreProfile/ScoreProfile.html
> +					<a>776</a>
Разве скорборд не должен подтягиваться с сервера (нодовского или гошного)? В фесте точно есть опции для итерации по объектам

2019-04-02 18:29 UTC, stanf0rd commented on public/components/profile/profile.css
> +.profile_container .profile_container_top .profile_data_1 .profile_data_bottom_border_div, .profile_container .profile_container_top .profile_data_2 .profile_data_bottom_border_div, .profile_containe
На основе чего сгенерены стили, не могу понять?
Выкиньте сгенеренные стили из проекта, создавайте их при запуске приложения.

2019-04-02 18:29 UTC, stanf0rd commented on public/main.js
> +local storage
Напомни, зачем localStorage?

2019-04-02 18:29 UTC, stanf0rd commented on public/main.js
> +  start();
Зачем стрелочная функция, если можно напрямую передавать функцию `start`?

2019-04-02 18:29 UTC, stanf0rd commented on public/models/MenuModel.js
> +    this.eventBus = eventBus;
Есть ли смысл везде передовать bus как параметр и позже сохранять его как объект класса, если у него есть единственный глобальный инстанс, который можно получать через, скажем,
`import { globalBus }` ?

2019-04-02 18:29 UTC, stanf0rd commented on public/models/ProfileModel.js
> +      const password = 'kostyl'; // секретный ключ, не запоминать
лол

2019-04-02 18:30 UTC, stanf0rd commented on public/modules/ajax.js
> +  doPromiseGet({path = '/'} = {}) {
Тогда стоит его выпилить, если не пользуетесь

2019-04-02 19:05 UTC, Vlad104 commented on public/models/MenuModel.js
> +    this.eventBus = eventBus;
Хорошая идея

2019-04-02 19:19 UTC, Vlad104 commented on public/main.js
> +local storage
В отличии от sessionStorage, localStorage позволяет хранить данные между сессиями, даже после закрытия браузера.
Нужен ли нам localStorage? Не знаю
Возможно будем хранить настройки игры (если такие вообще будут). Либо была идея, хранить там счет пользователя, пока он в оффлайне и синхронизировать с сервером, когда пользователь перейдет в онлайн

2019-04-02 19:32 UTC, Vlad104 commented on .eslintrc.js
> +            "jsx": true
Не знаю, либо скопировал где-то, либо при eslint --init сгенерировалось
Это нам не надо, можно убрать

2019-04-02 19:32 UTC, Vlad104 commented on package.json
> +    "eslint-config-google": "^0.12.0",
Ок, package.json действительно давно не чистили

2019-04-02 19:38 UTC, Vlad104 commented on public/components/ScoreProfile/ScoreProfile.html
> +	<title>Score Board</title>
Пробелы однозначно, иначе б мне eslint покоя не дал
Ток он у меня на js только смотрит (и хорошо)
А этот html не нужен, я его забыл удалить

2019-04-02 19:40 UTC, Vlad104 commented on public/components/ScoreProfile/ScoreProfile.html
> +					<a>776</a>
Эта штука у нас уже никуда не встроена, осталась со времен, когда сервера не было)

2019-04-02 19:45 UTC, Vlad104 commented on public/components/profile/profile.css
> +.profile_container .profile_container_top .profile_data_1 .profile_data_bottom_border_div, .profile_container .profile_container_top .profile_data_2 .profile_data_bottom_border_div, .profile_containe
Хорошо, но верстку и стили мы начнем немного позже переделывать. Руководствуясь бэм и используя (скорей всего) post css.
Все css у нас были написаны в самом начале работы на проектом и мы их до сих пор не трогали

2019-04-02 19:47 UTC, Vlad104 commented on public/main.js
> +  start();
Да, не подумал

2019-04-02 19:48 UTC, Vlad104 commented on public/models/ProfileModel.js
> +      const password = 'kostyl'; // секретный ключ, не запоминать
Сейчас просто лень не хочется лезть в верстку. А в ней, как можно догадаться, поля для пароля не было. Вот я и решил захардкодить, чтобы функционал пока тестировать

2019-04-04 14:16 UTC, stanf0rd approved these changes

2019-04-04 14:16 UTC, stanf0rd commented on package.json
> -    "morgan": "^1.9.1",
Морган, кстати, классная штука - очень удобный логгер. Маст-хэв, если пишете что-то на ноде. Запомните его себе где-нить)

2019-04-04 14:16 UTC, stanf0rd commented on public/main.js
> + * Пописака на события глобальной шины
:D

2019-04-04 14:16 UTC, stanf0rd commented on public/modules/eventbus.js
> +export { EventBus, GlobalBus };
Кстати, в js, как и в плюсах, удобно классы звать с заглавной буквы, а их инстансы - с маленькой. Глаз сходу цепляется за первую букву, выходит более интуитивно)

2019-04-04 16:21 UTC, merged