РК2
frontend-park-mail-ru/2019_1_WAO pull request #3
Opened 2019-04-14 14:08 UTC by Vlad104

https://wao2019.herokuapp.com/

2019-04-14 16:37 UTC, stanf0rd requested changes

2019-04-14 16:37 UTC, stanf0rd commented on package.json
> -    "webpack": "^4.29.6",
Куда убрали вебпак?)

2019-04-14 16:37 UTC, stanf0rd commented on package.json
>      "eslint-plugin-react": "^7.11.0",
Зачем анализаторы react и jsx?

2019-04-14 16:37 UTC, stanf0rd commented on public/components/about/about.css
> +.about__dev-team__member {
У вас трабблы с неймингом классов. Насколько я понимаю, вы хотите использовать БЭМ? Читали про методологию?
По БЭМ-у через `__` обозначаются элементы блоков. Если внутри блока в элемент вложен второй элемент - то в css такая вложенность не отображается, для такого элемента создаётся `.block__element2`

2019-04-14 16:37 UTC, stanf0rd commented on public/components/about/about.handlebars
> +        {{> ../title/title.handlebars title1}}
табуляция поехала, и в конце строк висят пробелы:
![image](https://user-images.githubusercontent.com/28190898/56094491-b17c2f80-5edd-11e9-82f0-57e004624263.png)

2019-04-14 16:37 UTC, stanf0rd commented on public/components/about/about.css
> +.about__dev-team__member {
Но мне кажется, дело тут не только в этом

У вас, по сути, получился очень большой блок about, внутри которого находится много элементов и ни одного блока. С одной стороны понятно, почему - приложение не очень большое, повторяющихся блоков почти нет, но с другой стороны - поиграть в БЭМ полезно :)
Я бы таки сделал внутренние блоки, пусть и не обязательно вынося их в отдельные файлы, если они не переиспользуются.

2019-04-14 16:37 UTC, stanf0rd commented on public/components/form-button/form-button.css
> +	box-shadow: 0 0 20px rgba(0, 0, 0, 0.4);
табы поехали

2019-04-14 16:37 UTC, stanf0rd commented on public/components/input/input.css
> +.input-area {
В этом файлике, кстати, по БЭМ-у сделано, топчик

2019-04-14 16:37 UTC, stanf0rd commented on public/components/form-button/form-button.css
> +	box-shadow: 0 0 20px rgba(0, 0, 0, 0.4);
Определитесь с количество пробелов/табов, настройте ваши IDE, и сделайте так, чтобы линтер это отслеживал

2019-04-14 16:37 UTC, stanf0rd commented on public/components/menu/Menu.css
> +.menu-bar {
Название файлика с маленькой буквы сделайте, либо везде с большой пишите

2019-04-14 16:37 UTC, stanf0rd commented on public/components/menu/__button/__button.tmpl.xml
> +<fest:template xmlns:fest="http://fest.mail.ru" context_name="data">
куски феста остались

2019-04-14 16:37 UTC, stanf0rd commented on public/components/scoreboard/ScoreBoard.css
> +.scoreboard__row__col-1 {
БЭМ отвалился чуток

2019-04-14 16:37 UTC, stanf0rd commented on public/components/signin/signin.css
> +	grid-gap: 10px;
опять табы

2019-04-14 16:37 UTC, stanf0rd commented on public/main.js
> +import './components/common/common.css';
Почему все компоненты большой пачкой импортятся в главном файле?

2019-04-14 16:37 UTC, stanf0rd commented on public/components/store/store.css
> +	text-align: center;
Боль
![image](https://user-images.githubusercontent.com/28190898/56095463-01f78b00-5ee6-11e9-85ff-7eff63d73d05.png)

2019-04-14 16:37 UTC, stanf0rd commented on public/views/MenuView.js
> +    super(el, eventBus, template, components, vievData);
Почему везде `viev`, а не view? Или я чего-то не понимаю?)

2019-04-14 16:37 UTC, stanf0rd commented on public/views/ProfileView.js
> +    super(el, eventBus, template, components, vievData);
Погугли про деструктуризацию.
Когда метод принимает много аргументов, можно запутаться в их порядке, или может понадобиться отправка только некоторых аргументов

В таких случаях полезно в самом методе принимать объект и на ходу его разбирать на параметры:
```javascript
method({ el, eventBus, template, components, vievData }) {
    ...
}
```

2019-04-14 16:37 UTC, stanf0rd commented on public/views/ScoreBoardView.js
> +import template from '../components/scoreboard/scoreboard.handlebars';
кстати - расширение файликов хэндлбарса выглядит как `.hbs`

2019-04-14 23:19 UTC, Vlad104 commented on public/views/ScoreBoardView.js
> +import template from '../components/scoreboard/scoreboard.handlebars';
![image](https://user-images.githubusercontent.com/22621714/56100711-d942b600-5f24-11e9-81c7-437d48ed9853.png)
vs code ставит им ярлык handlebars, значит норм)

2019-04-14 23:20 UTC, Vlad104 commented on public/views/MenuView.js
> +    super(el, eventBus, template, components, vievData);
сначала натыкал везде, потом ошибку увидел, так до конца и не исправил

2019-04-14 23:24 UTC, Vlad104 commented on public/components/menu/Menu.css
> +.menu-bar {
Да давно поменял. Но тут либо винда либо гит к регистру имен нечувствительны

2019-04-14 23:25 UTC, Vlad104 commented on package.json
>      "eslint-plugin-react": "^7.11.0",
реакт как-то сам поставился)
а без jsx vs code ошибки не подчеркивает

2019-04-14 23:25 UTC, Vlad104 commented on package.json
> -    "webpack": "^4.29.6",
в devDependencies

2019-04-14 23:28 UTC, Vlad104 commented on public/components/about/about.css
> +.about__dev-team__member {
Ок, хорошо

2019-04-15 08:00 UTC, stanf0rd commented on package.json
> -    "webpack": "^4.29.6",
звиняюсь, не заметил)

2019-04-15 08:19 UTC, stanf0rd commented on public/modules/bus.js
> +class Bus {
мммм, а зачем второй?

2019-04-15 08:19 UTC, stanf0rd commented on public/modules/game/game-scene/index.js
> +    // camelCase, Димас !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
:D

2019-04-15 08:19 UTC, stanf0rd commented on public/modules/game/game-scene/index.js
> +    for (const plateIndex in this.field) {
Разве `const` здесь, не `let`? Значение ведь меняется. Оно точно вот так работает?

2019-04-15 08:19 UTC, stanf0rd commented on public/modules/game/game-scene/index.js
> +        for (const key in this.me) {
ну судя по тому, что так везде, действительно можно `const`. Не думал, что так работает)

2019-04-15 08:19 UTC, stanf0rd commented on package.json
>      "eslint-plugin-react": "^7.11.0",
очень странно, надо будет потом вместе поковыряться

2019-04-15 08:21 UTC, stanf0rd approved these changes

2019-04-15 08:21 UTC, merged